MT4_TOP=D:/MinGW/msys/1.0/home/yuting/Alpari

#CCOPTS=-Wall -Werror -g -mthreads

.PHONY: all ea eainstall in ininstall



ea:
	@cd ea
	@echo "make ea"

eainstall: ea
	@echo "make eainstall"


in:
	@cd in
	@echo "make in"

ininstall:
	@cd in
	@echo "make ininstall"