#!/home/tops/bin/python

import os, sys ,re,string
import time
sys.path.append('/home/yuting/project/turbo-daytrader/forextools')
from forexsys_db_wrapper import ForexsysDb


a = ForexsysDb()
a.backup()

