#!/bin/sh

#console
#exec rdesktop -g 1024x768 shake.corp.linuxnote.net:3366

rdesktop -g 1024x768 -a 16 -K -xl -r clipboard:PRIMARYCLIPBOARD -r sound:local -T '$TITLE'  localhost:3389 

#rdesktop -g 1024x768 -u caiya -5 -a 16 -P -D -K -xl -z -r disk:D=$HOME/windrv -r clipboard:PRIMARYCLIPBOARD -r sound:local -T '$TITLE'  shake.corp.linuxnote.net -p '!QAZ2wsx'

