#!/bin/sh

#console
#exec rdesktop -g 1024x768 shake.corp.linuxnote.net:3366

rdesktop -g 1280x1024 -u yuting -5 -a 16 -P -D -K -xl -z -r disk:D=$HOME/windrv -r clipboard:PRIMARYCLIPBOARD -r sound:local -T 'shakeDesktop'  windows.corp.linuxnote.net -p '!QAZ2wsx'
