#!/bin/sh


resol=$(xrandr --screen 0 2>&1 |grep '*' |awk '{print $1}')

rdesktop -g $resol -u yuting -5 -a 16 -P -D -K -xl -z -r disk:D=$HOME/win -r clipboard:PRIMARYCLIPBOARD -r sound:local -T 'tingbox'  192.168.2.8
