#!/bin/bash

resol=$(xrandr --screen 0 2>&1 |grep '*' |awk '{print $1}')

/usr/bin/rdesktop -g $resol -u yuting  -5 -a 16 -P -D -K -xl -z -r disk:D=$HOME/windrv -r clipboard:PRIMARYCLIPBOARD  -T 'shakeDesktop'  windows.corp.linuxnote.net 
