* STARTED runin 脚本
  :LOGBOOK:
  CLOCK: [2011-09-29 Thu 12:40]--[2011-09-29 Thu 13:08] =>  0:28
  :END:
[2011-09-29 Thu 12:39]
[[file:~/org/health_ent.org::*%E5%90%83%E9%A5%AD][吃饭]]
	support run cmd in some directory

* NEXT 把 spkg clone 到本机笔记本上
  :LOGBOOK:
  CLOCK: [2011-09-29 Thu 13:08]--[2011-09-29 Thu 13:14] =>  0:06
  :END:
[2011-09-29 Thu 13:08]
[[file:~/org/refile.org::*runin%20%E8%84%9A%E6%9C%AC][runin 脚本]]
* TODO 配置 imapd + ssl
  :LOGBOOK:
  CLOCK: [2011-09-29 Thu 18:05]--[2011-09-29 四 18:15] =>  0:10
  :END:
[2011-09-29 Thu 18:05]
[[file:~/org/gemstone.org::*%E9%85%8D%E7%BD%AE%20yasnippet%20&%20flymake][配置 yasnippet & flymake]]
 

* TODO 回购
  :LOGBOOK:
  CLOCK: [2011-10-08 Sat 11:30]--[2011-10-08 Sat 11:40] =>  0:10
  :END:
[2011-10-08 Sat 11:30]
[[gnus:Junk#1750506965.23141316708747540.JavaMail.root@UNKNOWN.aliyun.com][Email from SHARES@alibaba-inc.com: 第三方投资人投标要约购买阿里巴]]

https://shares.alibaba.com/shares/user/clientPassWord.action?encryptUserName=D94E37406A9E6B5BCB504D17AB8F7B7BD5E5E3622FD9117550216682B2E83AE4F06271348A0FD4D7


* TODO 给postgresql 打一个 tops 包
  :LOGBOOK:
  CLOCK: [2011-10-09 Sun 12:10]--[2011-10-09 Sun 15:01] =>  2:51
  :END:
[2011-10-09 Sun 12:10]
[[file:~/org/refile.org::*%E5%B8%AElidun%20%E6%90%9E%E5%AE%9A%20postgresql%20hstore][帮lidun 搞定 postgresql hstore]]
  - http://wwwmaster.postgresql.org/download/mirrors-ftp/source/v9.1.1/postgresql-9.1.1.tar.bz2
    
* 如何通过 emacs 编辑系统下root权限的东西 			       :NOTE:
   :LOGBOOK:
   CLOCK: [2011-10-10 一 07:26]--[2011-10-10 一 07:29] =>  0:03
   :END:
[2011-10-10 一 07:26]
[[id:eb155a82-92b2-4f25-a3c6-0304591af2f9][Organization]]
   /sudo::/etc/hosts
* TODO procmail 规则有问题
  :LOGBOOK:
  CLOCK: [2011-10-11 Tue 14:26]--[2011-10-11 Tue 14:28] =>  0:02
  :END:
[2011-10-11 Tue 14:26]
[[gnus:Greetings#201101240409.p0O4331R005555@nagios.taobao.ali.com][Email from it@taobao.com: 【006617/不平/陆研】给您送来了]]

	- 当前情况是大部分的邮件都命中了 Junk 的规则. 怀疑是规则信息有问题.
	- 需要解决的问题. 如何建立一个空的 bincmap.
* iptables 相关配置和fanye的讨论结果，参考yst-iptables的实现制作 		       :NOTE:
   :LOGBOOK:
   CLOCK: [2011-10-12 Wed 14:39]--[2011-10-12 Wed 14:40] =>  0:01
   :END:
[2011-10-12 Wed 14:39]
[[file:~/org/refile.org::*%E9%85%8D%E7%BD%AE%20imapd%20%2B%20ssl][配置 imapd + ssl]]

严庄 2011-10-12 14:15:27
 http://pastebin.corp.linuxnote.net/show/46/
严庄 2011-10-12 14:15:40
 这个是以前我们管理iptable 的那个脚本。。
严庄 2011-10-12 14:16:41
 他里面会load 一堆 iptable 相关的规则和 module
严庄 2011-10-12 14:17:10
 http://pastebin.corp.linuxnote.net/show/47/
严庄 2011-10-12 14:17:25
 这个是 iptables-modules . 
严庄 2011-10-12 14:20:23
 http://pastebin.corp.linuxnote.net/show/48/
严庄 2011-10-12 14:20:48
 这个是 iptables-blessed
严庄 2011-10-12 14:22:15
 http://pastebin.corp.linuxnote.net/show/49/
严庄 2011-10-12 14:22:25
 这个是 iptalbes-post-blessed
严庄 2011-10-12 14:24:00
 http://pastebin.corp.linuxnote.net/show/50/
严庄 2011-10-12 14:24:11
 这个是 iptables-pre-raw
严庄 2011-10-12 14:24:26
 那个perl 脚本很简单.
严庄 2011-10-12 14:33:08
 这个 iptable load 的脚本里面没有 NAT 相关的连定义。。只有 
严庄 2011-10-12 14:33:09
    # link tables to each other
    run($iptables, '-A', 'pre-blessed', '-j', 'blessed');
    run($iptables, '-A', 'blessed', '-j', 'post-blessed');
    #output tables
    run($iptables, '-A', 'pre-blessed-output', '-j', 'blessed-output');
    run($iptables, '-A', 'blessed-output', '-j', 'post-blessed-output');
严庄 2011-10-12 14:33:29
 ================
严庄 2011-10-12 14:33:30
         # link top to input chain
        run($iptables, '-A', 'INPUT', '-j', 'pre-blessed');
        run($iptables, '-A', 'OUTPUT', '-j', 'pre-blessed-output');
严庄 2011-10-12 14:33:35
 这两部分的..
严庄 2011-10-12 14:33:43
 关于 NAT的。可以简单仿造加上一个。。
严庄 2011-10-12 14:33:57
 然后加上 NAT的规则链。。
严庄 2011-10-12 14:33:59
 这样就ok了。/
严庄 2011-10-12 14:35:25
 具体实现上，如果web 和 soc 库上都设计差不多了。。
严庄 2011-10-12 14:35:38
 我们可以拉上时迁到时候一起讨论一下。。
严庄 2011-10-12 14:35:57
 应该基本上没有什么太大的问题。。
严庄 2011-10-12 14:37:39
 load iptable 的配置和 fetch iptable 的程序我们最好分离。
严庄 2011-10-12 14:38:14
 这样。。未来部署的时候会更灵活，安全。。不会因为一个脚本失败而失败。
* TODO 确定pyrange 默认的 altpath
  :LOGBOOK:
  CLOCK: [2011-10-12 Wed 14:48]--[2011-10-12 Wed 14:49] =>  0:01
  :END:
[2011-10-12 Wed 14:48]
[[file:~/org/gemstone.org::*%E9%85%8D%E7%BD%AE%20yasnippet%20&%20flymake][配置 yasnippet & flymake]]

	需要把默认的pyrange 的 altpath 设置成 /home/tops/tools/conf
